FileVersion = 1

[Project]
Name = "amoeba-beef"
DefaultNamespace = "amoeba"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\x86_64-windows-msvc\\amoeba_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\x86_64-windows-msvc\\amoeba.lib"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)\\libs\\x86_64-windows-msvc\\amoeba_d.lib"]
