FileVersion = 1

[Project]
Name = "amoeba-beef"
DefaultNamespace = "amoeba"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\x86_64-windows-msvc\\amoeba_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\x86_64-windows-msvc\\amoeba.lib"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)\\libs\\x86_64-windows-msvc\\amoeba_d.lib"]

[Configs.Debug.Linux64]
LibPaths = ["$(ProjectDir)\\libs\\x86_64-linux-musl\\libamoeba_d.a"]

[Configs.Release.Linux64]
LibPaths = ["$(ProjectDir)\\libs\\x86_64-linux-musl\\libamoeba.a"]

[Configs.Test.Linux64]
LibPaths = ["$(ProjectDir)\\libs\\x86_64-linux-musl\\libamoeba_d.a"]

[Configs.Debug.macOS]
LibPaths = ["$(ProjectDir)\\libs\\aarch64-macos\\libamoeba_d.a"]

[Configs.Release.macOS]
LibPaths = ["$(ProjectDir)\\libs\\aarch64-macos\\libamoeba.a"]

[Configs.Test.macOS]
LibPaths = ["$(ProjectDir)\\libs\\aarch64-macos\\libamoeba_d.a"]
