name: Build All
run-name: Run tests for all platforms
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        # os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      - uses: https://codeberg.org/mlugg/setup-zig@v2
      - run: |
          zig build --prefix libs